### ISSUE TITLE
Be gentle with OSX

### ISSUE THREAD

**Issue by casimir** [jwilm/racerd#1]
About the _OSX Issues_ in your README. Instead of overriding Openssl's version for the whole system you could do it for this project only. I personally use this with `rustc`:
```
export OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib
export OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
```
It works well without forcing anything.

**Comment by jwilm** [comment]
Hey that's a great tip. Thanks for sharing :). Somehow this issue snuck into the tracker without me noticing.. sorry for the delayed response! I'll ensure this makes it into the README.

**Comment by jwilm** [comment]
@casimir I updated the README on a branch [rendered here](https://github.com/jwilm/racerd/blob/47d38c57d436b200c946bc5adc19a1c127c0183e/README.md). My version is slightly different than what you suggested, and I wanted to check with you that it solves the problem. Would you mind taking a quick look?

**Comment by casimir** [comment]
For me `pkg-config` give the system's version path (`/usr`). If you want to use homebrew binaries without force linking I think you can't use `pkg-config`, although a variable is way more clean something like `$(brew --prefix)/opt/openssl/lib` would work.

PS: I don't know how homebrew generate the flags info in `brew info openssl` but it should but this is basically the same values.

**Comment by jwilm** [comment]
I've decided to not address setting up openssl on OSX in the readme. Instead, the readme outlines requirements for building and gives a link to the rust-openssl instructions for manual setup.

**Comment by casimir** [comment]
Fair enough 😊
