### ISSUE TITLE
expose context and kind in /find_definition

### ISSUE THREAD

**Issue by henriiik** [jwilm/racerd#14]
The API does not expose context and kind for the `POST /find_definition` endpoint, unlike the corresponding racer CLI command. Is this something that you would consider adding?

### Background:
Yesterday i started to port [my VSCode extension](https://github.com/henriiik/vscode-rust) from racer CLI to racerd. VSCode allows you to display information when the user hovers over something as well as showing the function signature while entering function arguments.

Kind and context on hover (although it does not show up, the cursor is hovering over the hello function call):
![racer-hover](https://cloud.githubusercontent.com/assets/392416/12317456/c7ebb20c-ba91-11e5-8ef2-5c8d227c4064.PNG)

Context as function signature (although it does not show up, the carret is between the parens of the hello function call):
![racer-signature](https://cloud.githubusercontent.com/assets/392416/12317455/c7eba50a-ba91-11e5-9255-64f3992fbabc.PNG)

**Comment by henriiik** [comment]
I forked and implemented this in henriiik/racerd@f7f73a77dd5604db4b663cc769457b66884f7422. 

I can send a pull-request if you are interested. :)

**Comment by jwilm** [comment]
I would love a pull request for this! Nice work. :smile:
