### ISSUE TITLE
Secret file contents enforced to be UTF-8

### ISSUE THREAD

**Issue by Valloric** [jwilm/racerd#24]
I'm porting ycmd to be Python 2 & 3 compatible so I'm auditing the way we handle strings vs. bytes. Anyway, I noticed that racerd insists that the contents of the secret file it reads must be UTF-8 because it [puts those contents into a rust `String`](https://github.com/jwilm/racerd/blob/9b63607132ab7f9aa32eb85eb45707c1b8f70990/src/lib.rs#L70) (which enforces UTF-8 contents). 

That strikes me as wrong. The secret should be allowed to be any sequence of bytes.

All of this works in ycmd because the racerd completer [generates a random set of bytes, but encodes them with base64.](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/rust/rust_completer.py#L384) That shouldn't be necessary.

If racerd merely read the file bytes as a`[u8]`, clients would have an easier time (no need to enforce UTF-8 key).

**Comment by jwilm** [comment]
This makes a lot of sense. Adding it to the list...
