### ISSUE TITLE
Should show type info for fields instead of the field name

### ISSUE THREAD

**Issue by Manishearth** [jwilm/racerd#26]
![screenshot from 2016-02-05 03 17 59](https://cloud.githubusercontent.com/assets/1617736/12830809/31e044da-cbb7-11e5-9313-6ee66df708ba.png)

When suggesting a function, it correctly shows the full signature in the third column, however it doesn't do this for struct fields.

**Comment by jwilm** [comment]
I seem to recall this missing from Racer.

/cc @phildawes

**Comment by Manishearth** [comment]
I'm working on a fix

**Comment by jwilm** [comment]
Awesome! I have been wanting this too 😁

**Comment by Manishearth** [comment]
done, https://github.com/phildawes/racer/issues/500

**Comment by Manishearth** [comment]
Got to say, YCM's GoTo for Rust makes it super easy to grok new code. Pretty obvious I guess but I used it like crazy when figuring this one out, and it worked really well :smile:

**Comment by jwilm** [comment]
> done, phildawes/racer#500

You are a wonderful person. Thank you!

It looks like you updated the value of contextstr, so the only change needed for racerd is to update the racer dependency. I'll get that done after your patch lands and also update the racerd ref in ycmd.

> Got to say, YCM's GoTo for Rust makes it super easy to grok new code

This is why racerd exists. :grin:

**Comment by jwilm** [comment]
@Valloric you have another happy customer

**Comment by Valloric** [comment]
> @Valloric you have another happy customer

Aw yiss. :)

And I see we'll be getting type info for struct members soon too! Thank you @Manishearth! :D

**Comment by jwilm** [comment]
This landed a while ago.

![screenshot from 2016-05-15 16 08 13](https://cloud.githubusercontent.com/assets/4285147/15277386/4a7b41bc-1ab7-11e6-9ac4-1074e0f1823e.png)
