### ISSUE TITLE
Can't complete Vec like in gif with rust nigthly

### ISSUE THREAD

**Issue by oblitum** [jwilm/racerd#43]
I'm trying to complete a trivial sample, just following the gif of your release blog post, but I was unable to complete `Vec`. Do you know what it may be?

Also, this time, compilation was not successful with nightly and I had to apply this patch because warnings are being treated as errors, and there are unused symbols imported:

```diff
diff --git a/src/http/completion.rs b/src/http/completion.rs
index 6026674..6332319 100644
--- a/src/http/completion.rs
+++ b/src/http/completion.rs
@@ -4,7 +4,7 @@ use iron::mime::Mime;

 use rustc_serialize::json;

-use engine::{SemanticEngine, Completion, Context, CursorPosition, Buffer};
+use engine::{Completion, Context, CursorPosition, Buffer};
 use super::EngineProvider;

 /// Given a location, return a list of possible completions
diff --git a/src/http/definition.rs b/src/http/definition.rs
index 5468b84..71bbf1c 100644
--- a/src/http/definition.rs
+++ b/src/http/definition.rs
@@ -5,7 +5,7 @@ use iron::mime::Mime;

 use rustc_serialize::json;

-use engine::{SemanticEngine, Definition, Context, CursorPosition, Buffer};
+use engine::{Definition, Context, CursorPosition, Buffer};
 use super::EngineProvider;

 /// Given a location, return where the identifier is defined
```

**Comment by oblitum** [comment]
I've run the server standing alone and run the tests, all passing. I've then tried a request example that completes `path` from `std`, and it works. In Vim, I do can complete `path`, but not `Vec`.

**Comment by jwilm** [comment]
Re: patch
we just landed #40 a few days ago which should have that patch on master.

Re: Vec completion
Is that on master with your patch applied? Also, what version of the rust source do you have?

**Comment by oblitum** [comment]
Re: patch
Ah ok, I dunno what happened then, I've reinstalled it not standing alone but by building YCM again, but it didn't pick that changeset, I'll try again, if it doesn't update, I'll pull the master inside the directory because it should be somehow pinned when building with YCM.

Re: Vec completion
Just before I opened this I've installed rustup, installed the latest nightly, and updated my copy of the rust repository with `git pull --recurse-submodules`. Rust sources are at https://github.com/rust-lang/rust/commit/e7420fbbae85a62a62163a2ac5c947b76a8eb62d.

**Comment by jwilm** [comment]
I looked all over the commit page you linked to find a date; it seems crazy that GitHub wouldn't put it there! Anyway, it looks like you've got the very latest rustc source. Maybe something changed and Racer needs to be updated? I can look into this later. Thanks for the report!

**Comment by oblitum** [comment]
@jwilm there's just "a day ago"... Thanks, I'll also give it a second look about the racerd updating process, not sure why I didn't get the patch already.

**Comment by jwilm** [comment]
The racerd ref was just updated in ycmd yesterday; I wouldn't be surprised it YouCompleteMe hasn't updated the ycmd ref yet.

**Comment by jwilm** [comment]
Also, thanks on the date thing. Somehow overlooked that several times XD.

**Comment by oblitum** [comment]
haha, me too.

**Comment by jwilm** [comment]
I was able to complete `v.` as in the following snippet with the latest nightly rustc source, and the latest racerd compiled with 1.8.

```rust
fn main() {
    let v: Vec<i32> = Vec::new();
    v.
    println!("Hello, world!");
}
```

Currently building with the latest nightly compiler to test with that... and it seems to still work.

Is there any other info I need to reproduce this?

**Comment by oblitum** [comment]
Thanks for your time into this. This time, instead of applying the patches, I've pulled the master and rebuilt YCM. In doing so it has compiled again everything rust related, after that, the issue is gone. I've built it with my nightly copy.

**Comment by jwilm** [comment]
Glad to hear it's resolved!
