### ISSUE TITLE
Idea: Adopt Common Language Service Protocol

### ISSUE THREAD

**Issue by LeDominik** [jwilm/racerd#49]
This is just an idea, but wouldn't it speed up tool adoption to adopt the [language service protocol](https://github.com/Microsoft/language-server-protocol) that is now used by [Visual Studio Code](http://code.visualstudio.com/blogs/2016/06/27/common-language-protocol) and [Eclipse Ché](http://che.eclipse.org/eclipse-che-now-strategic-platform-red-hat/)?

There's already **[a few languages supported](https://github.com/Microsoft/language-server-protocol/wiki/Protocol-Implementations)** and after trying out the [Java-Integration vor Visual Studio Code](https://github.com/georgewfraser/vscode-javac) yesterday (see their [implementation issue](https://github.com/georgewfraser/vscode-javac/issues/3)) I have to say the ergonomics from a user perspective are really good.

My assumption is that adopting this protocol _could_ speed up adoption within all those editors and IDE's considerably making Rust a first-class citizen. Of course if this proves _useful_ then this could be the lingua franca [for racer directly](https://github.com/phildawes/racer/issues/457) further reducing the moving parts, dreaming here...

**Comment by jwilm** [comment]
Thanks for the suggestion. Since racerd was built with the express purpose of supporting YCM, and the forthcoming RLS will replace it, this doesn't make sense for the project. Once RLS support lands in YCM, racerd will become a relic.
