### ISSUE TITLE
some completion is wrong

### ISSUE THREAD

**Issue by phynalle** [jwilm/racerd#56]
I'm vim with YCM and racer-completer and I have a problem about completion.
see screenshots below and check out differences.

the version of 0.1.0
the correct result
![expected](https://cloud.githubusercontent.com/assets/6007810/18723142/6f39a234-8072-11e6-85c9-143d0970b92e.png)
![expected2](https://cloud.githubusercontent.com/assets/6007810/18723146/7288d02c-8072-11e6-9f31-17f1ba92563a.png)

the version >= 0.2
![wrong](https://cloud.githubusercontent.com/assets/6007810/18722228/04a64b96-806f-11e6-835e-5176775e458c.png)
![wrong2](https://cloud.githubusercontent.com/assets/6007810/18723121/6090622c-8072-11e6-9f9e-4e138ae9d18c.png)
this result is surely wrong because std::process::Command structure (not object) cannot have member functions having self parameter. right?

I tried to change the version of racer and racerd respectively and I found the problem occurred on the version >= 0.2.
I hope it will be fixed.

**Comment by jwilm** [comment]
Hey there,

Thanks for posting the issue. This is an issue with _racer_ actually, so it'll need to be fixed there and then _racerd_ can make a release. Leaving this open as a reminder to release once it's fixed.

**Comment by jwilm** [comment]
This is actually working as expected. Please see the discussion on racer for details.
