### ISSUE TITLE
v0.31 Compile failed 

### ISSUE THREAD

**Issue by Matrix-Zhang** [jwilm/racerd#60]
Compiling libracerd v0.3.1 (file:///home/matrix/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/racerd)
error: type alias is never used: `ListCompletionsResponse`
   --> /home/matrix/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/racerd/target/release/build/libracerd-ccd438395932b4cf/out/http/completion.rs:281:1
    |
281 | type ListCompletionsResponse = Vec<CompletionResponse>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lint level defined here
   --> src/lib.rs:9:9
    |
9   | #![deny(warnings)]
    |         ^^^^^^^^

**Comment by little-dude** [comment]
@Matrix-Zhang here is a quick&dirty workaround if you want rust complettion:

```
cd ${YOUR_VIM_PLUGIN_DIRECTORY}/YouCompleteMe/third_party/ycmd/third_party
# replace the racer directory by my fork, which contains the fix
rm -rf racerd
git clone https://github.com/little-dude/racerd/
cd ../../..
# install rust completion for ycm
python install.py --racer-completer
# cleanup so that your plugin manager won't complain next time you update ycm
git reset --hard origin/master   # not sure if this is necessary, but it does not hurt
cd third_party/ycmd 
git submodule update --init
```
