### ISSUE TITLE
src/http/mod.rs:94 on os X 10.11.6

### ISSUE THREAD

**Issue by huoyuanliao** [jwilm/racerd#69]
chain.link_before(Write::<EngineProvider>::one(Box::new(engine)));
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `persistent::PersistentInto<std::sync::Arc<std::sync::Mutex<std::boxed::Box<engine::SemanticEngine + std::marker::Sync + std::marker::Send + 'static>>>>` is not implemented for `std::boxed::Box<E>`

**Comment by ethe** [comment]
I got the same error.
